export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOAD_USER = "LOAD_USER"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"
export const LOGOUT_USER = "LOGOUT_USER"

export const SET_LOADING = "SET_LOADING"

export const CREATE_PROJECT = "CREATE_PROJECT"
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR"
export const GET_ALL_PROJECT = "GET_ALL_PROJECT"
export const GET_ALL_PROJECT_ERROR = "GET_ALL_PROJECT_ERROR"
export const SINGLE_PRODUCT = "SINGLE_PRODUCT"
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR"



